import { motion } from 'framer-motion';
import { format } from 'date-fns';
import { Button } from '@/components/ui/button';
import { Receipt, RefreshCw, Download, Clock, Users, DollarSign, TrendingUp } from 'lucide-react';
import type { MeetingConfig, MeetingData } from '@/hooks/useMeetingTimer';
import { formatCurrency } from '@/lib/equivalences';

interface MeetingReceiptProps {
  config: MeetingConfig;
  data: MeetingData;
  formatTime: (seconds: number) => string;
  onNewMeeting: () => void;
}

export function MeetingReceipt({ config, data, formatTime, onNewMeeting }: MeetingReceiptProps) {
  const costPerMinute = data.totalCost / Math.max(1, data.elapsedSeconds / 60);
  const costPerPerson = data.totalCost / config.attendees;

  const handleExport = () => {
    // Create a simple text receipt for clipboard
    const receiptText = `
━━━━━━━━━━━━━━━━━━━━━━━━━━
       MEETING RECEIPT
━━━━━━━━━━━━━━━━━━━━━━━━━━

Date: ${data.startTime ? format(data.startTime, 'PPP') : 'N/A'}
Time: ${data.startTime ? format(data.startTime, 'p') : 'N/A'} - ${data.endTime ? format(data.endTime, 'p') : 'N/A'}

Duration:     ${formatTime(data.elapsedSeconds)}
Attendees:    ${config.attendees}
Hourly Rate:  ${formatCurrency(config.hourlyRate, config.currency)}/person

━━━━━━━━━━━━━━━━━━━━━━━━━━
TOTAL COST:   ${formatCurrency(data.totalCost, config.currency)}
━━━━━━━━━━━━━━━━━━━━━━━━━━

Cost/minute:  ${formatCurrency(costPerMinute, config.currency)}
Cost/person:  ${formatCurrency(costPerPerson, config.currency)}

Generated by MeetingBurner 🔥
    `.trim();

    navigator.clipboard.writeText(receiptText);
  };

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-md mx-auto"
    >
      {/* Receipt Container */}
      <div className="receipt p-8 my-8 text-background">
        {/* Header */}
        <div className="text-center mb-6">
          <Receipt className="w-10 h-10 mx-auto mb-2 opacity-60" />
          <h2 className="text-2xl font-bold tracking-tight">MEETING RECEIPT</h2>
          <div className="text-sm opacity-70 mt-1">
            {data.startTime && format(data.startTime, 'PPP')}
          </div>
        </div>

        {/* Divider */}
        <div className="border-t-2 border-dashed border-background/20 my-4" />

        {/* Details */}
        <div className="space-y-3 text-sm">
          <div className="flex justify-between">
            <span className="flex items-center gap-2 opacity-70">
              <Clock className="w-4 h-4" /> Duration
            </span>
            <span className="font-bold">{formatTime(data.elapsedSeconds)}</span>
          </div>

          <div className="flex justify-between">
            <span className="flex items-center gap-2 opacity-70">
              <Users className="w-4 h-4" /> Attendees
            </span>
            <span className="font-bold">{config.attendees}</span>
          </div>

          <div className="flex justify-between">
            <span className="flex items-center gap-2 opacity-70">
              <DollarSign className="w-4 h-4" /> Hourly Rate
            </span>
            <span className="font-bold">{formatCurrency(config.hourlyRate, config.currency)}/person</span>
          </div>
        </div>

        {/* Divider */}
        <div className="border-t-2 border-dashed border-background/20 my-4" />

        {/* Total */}
        <div className="text-center py-4">
          <div className="text-xs uppercase tracking-wider opacity-70 mb-1">Total Cost</div>
          <div className="text-4xl font-bold tracking-tight">
            {formatCurrency(data.totalCost, config.currency)}
          </div>
        </div>

        {/* Divider */}
        <div className="border-t-2 border-dashed border-background/20 my-4" />

        {/* Additional Stats */}
        <div className="grid grid-cols-2 gap-4 text-xs">
          <div className="text-center p-2 bg-background/5 rounded">
            <div className="opacity-70 mb-1">Cost/Minute</div>
            <div className="font-bold">{formatCurrency(costPerMinute, config.currency)}</div>
          </div>
          <div className="text-center p-2 bg-background/5 rounded">
            <div className="opacity-70 mb-1">Cost/Person</div>
            <div className="font-bold">{formatCurrency(costPerPerson, config.currency)}</div>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center mt-6 text-xs opacity-50">
          <p>Generated by MeetingBurner 🔥</p>
          <p>{data.endTime && format(data.endTime, 'PPpp')}</p>
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-3 mt-6">
        <Button
          variant="outline"
          onClick={handleExport}
          className="flex-1 h-12 border-muted-foreground/20 hover:bg-muted"
        >
          <Download className="w-4 h-4 mr-2" />
          Copy to Clipboard
        </Button>
        <Button
          onClick={onNewMeeting}
          className="flex-1 h-12 bg-primary hover:bg-primary/90"
        >
          <RefreshCw className="w-4 h-4 mr-2" />
          New Meeting
        </Button>
      </div>
    </motion.div>
  );
}
